POST https://localhost:5001/Pool
Content-Type: application/json

{
    "name_Pool": "Dragon Club",
    "location":"Real de palmas",
    "temp_min":18.5,
    "temp_max":40.5,
    "temp_current":20,
    "ph_min":2,
    "ph_max":11,
    "ph_current":7,
    "grados": "f",
    "idUser":"60d378a5b55bd4028994fb27"
}
###
GET https://localhost:5001/Pool/60d68ff4cb6b8ca45edab115
###
GET https://localhost:5001/Pool/user/60c3978a0c1d417146b5572a
###
PUT https://localhost:5001/Pool
Content-Type: application/json

{
    "id": "60d68ff4cb6b8ca45edab115",
    "name_Pool": "Piscina de los super malos",
    "location":"China, Monterrey",
    "temp_min":18.5,
    "temp_max":40.5,
    "temp_current":20,
    "ph_min":4,
    "ph_max":10,
    "ph_current":1.1,
    "grados": "f",
    "idUser":"60c3978a0c1d417146b5572a"
}
###
DELETE  https://localhost:5001/Pool/60d0a9b7ba320d68ba2a7dd7


